spring:
  cloud:
    consul:
      host: consul
      port: 8500
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key: ${RSA_PUBLIC_KEY}

  datasource:
    url: ${PROBLEM_SPRING_DATASOURCE_URL}
    username: ${PROBLEM_SPRING_DATASOURCE_USERNAME}
    password: ${PROBLEM_SPRING_DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092