services:

  user-service:
    build:
      context: ./user-service/user-service-impl
    ports:
      - "8083:8080"
    networks:
      - app-net
    depends_on:
      localRabbitMQ:
        condition: service_healthy
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file: leetcode.conf
    restart: on-failure

  problem-service:
    build:
      context: ./problem-service/problem-service-impl
    ports:
      - "8081:8081"
    networks:
      - app-net
    depends_on:
      problem-postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=${PROBLEM_SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${PROBLEM_SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PROBLEM_SPRING_DATASOURCE_PASSWORD}
    env_file: leetcode.conf
    restart: on-failure

  submission-service:
    build:
      context: ./submission-service/submission-service-impl
    ports:
      - "8082:8080"
    networks:
      - app-net
    depends_on:
      mongodb:
        condition: service_started
      kafka:
        condition: service_healthy
      localRabbitMQ:
        condition: service_healthy
      consul:
        condition: service_started
    env_file: leetcode.conf
    restart: on-failure

  notification-service:
    build:
      context: ./notification-service/notification-service-impl
    ports:
      - "8084:8080"
    networks:
      - app-net
    depends_on:
      mongodb:
        condition: service_started
      kafka:
        condition: service_healthy
    env_file: leetcode.conf
    restart: on-failure

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    env_file: leetcode.conf
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5

  problem-postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    volumes:
      - problem_pg_data:/var/lib/postgresql/data
    networks:
      - app-net
    environment:
      - POSTGRES_DB=problem_service_db
      - POSTGRES_USER=elise
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file: leetcode.conf
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U elise -d problem_service_db" ]
      interval: 3s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db
    networks:
      - app-net
    env_file: leetcode.conf
    restart: unless-stopped

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-net
    env_file: leetcode.conf
    restart: unless-stopped

  localRabbitMQ:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-net
    env_file: leetcode.conf
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-net
    env_file: leetcode.conf
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app-net
    depends_on:
      - zookeeper
    env_file: leetcode.conf
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 5

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
    networks:
      - app-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    networks:
      - app-net
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - app-net
    restart: unless-stopped

volumes:
  mongo_data:
  problem_pg_data:
  redis_data:
  kafka_data:
  postgres_data:
  rabbitmq_data:

networks:
  app-net:
    driver: bridge