services:
  user-service:
    build:
      context: ./user-service/user-service-impl
    ports:
      - "8083:8080"
    networks:
      - app-net
    depends_on:
      - localRabbitMQ
      - postgres
      - kafka
    env_file: leetcode.conf

  notification-service:
    build:
      context: ./notification-service/notification-service-impl
    ports:
      - "8084:8080"
    networks:
      - app-net
    depends_on:
      - mongodb
      - kafka
    env_file: leetcode.conf

  localRabbitMQ:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - app-net
    env_file: leetcode.conf
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    env_file: leetcode.conf

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db
    networks:
      - app-net
    env_file:
      leetcode.conf

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-net
    env_file: leetcode.conf

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    container_name: kafka
    restart: always
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app-net
    depends_on:
      - zookeeper
    env_file: leetcode.conf

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app-net

volumes:
  mongo_data:
  problem_pg_data:
  redis_data:
  kafka_data:
  postgres_data:
  rabbitmq_data:

networks:
  app-net:
    driver: bridge