POSTGRES_DB=agona_db
POSTGRES_USER=Ekaterina
POSTGRES_PASSWORD=eka_rina16

SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/agona_db
SPRING_DATASOURCE_USERNAME=Ekaterina
SPRING_DATASOURCE_PASSWORD=eka_rina16

RABBITMQ_DEFAULT_USER=user
RABBITMQ_DEFAULT_PASS=password

OAUTH2_CLIENT_ID=my-client-id
OAUTH2_CLIENT_SECRET=my-client-secret

GOOGLE_CLIENT_ID=312079138201-a5on2274ietg9e29pqj3486olga0fctr.apps.googleusercontent.com

RSA_PRIVATE_KEY=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCIWWmR7NrJOA4zkESkB/z5dEw1oXjq8SzEQzdIc0R0NTVQwMFrDJ/W611f2os3GIJyqFZVIRi/Unvlkrv2TsWdixJTdXjKMVJXHfPdaCNi7zBpTZhR0lHqzX6Isjen0aeViyAFMYSQczoMSQlud3Zyue1KDoEiafcxsHjed5w5pFDut7+vX8rI56b/CLdh7yNAjJQ0hRlnci2CXhBeiYKIssN2TJj4YN2xUpjvCLZpQEXN7St0BxBZmev81rZcd3edKm8ta5ptLvwrYYy/d+Kujmjs1JWQQ8G1lfYML9r9llZTVUXbvOFNOQ+MD97Kucv7aLmys8SDTKM2emVshhQjAgMBAAECggEAIcR3Azcz9epmhfmgLjl2OrdFGnEbd5/z9MUqv0wgs2DsC8w4+pB9U2Yl0VPX73Sn9cpf2yRfsx4z5eahmz3l7f7fsoCgwf5WBJI772TXgqx3AlU/uF/MfsiWojb01qBzDvOOIgsh5/5JbXp3Ff8K/B20uQb/jyzMFee8/2eC7rk47CneKvvc9SihgyFHWhZD6EQ+dboKTDnADAauWKb6y7wRzsIH+aISN8BSebS75GTGVa3GqMLi39A5y5mqVTTEpBLehjuTEEBI7h7J2PhvEwg4DPD2vcBkL7OZbZ9X/dwBgUQ6sIOAvbQIDd9EVIhu3Fg0P4jy/5hLiihRBUdYKQKBgQC+7qOQ6BIK/BDcZLpEcitkahgtAEpG6vM3CtEXwoMMw/VNIs6Bqgx8cicTUTVO8CiYCQCqbdRYADLyS4A9oLgtw90UCY66lMGAvvK12EK4Sgv6KMnE24ylgIxAnzPOwv8KWkxi44RNRToYi5xvLyIg2GcxjUhlDcv8j1D5/ovIqQKBgQC20NW1nUrdHQ7WV2rbJDsdKIyykRmQn3ajaT29Fe2IMA9mrqlmPwFw63idnUU8GItyhQDAO6a+FFjzn3nJtHdsGBHcDKLFTXbLB754BJiGhZynUw3DCxW7Znsm/nvufnYW3pR//+Aq9y2JrJ8XgRUIPTIWOz7uvPjkgbQndpV56wKBgG8SSmro5l4nhvN/UXCx7hZLNecv7QXWdkiF7V9iE3SgppoJ7pI1x2+5xIuTSWyzfxn62r1KiSXsb7bOPzsavSo6b+jRKovWL79i1bT9qsqkoNUVV1NC2U4KOwz40F2uyElQgHFio7uD0ykmRonTpInw+g80fnHzFcDF6riT4OOJAoGBALK+8ZWHW4FiPfWYt2PYwuu5kAewE3zyTX9tEO5mGD9GLmjJcdwE0pXjxaTl9qHRpdas8JUEPf4vyuE5Fkz/ZJyN1DiBKk0bdoEA61xRsgglb4uyiwwfNHpssxDnValUgIXPzwZv2nBoCWBJJaxHi5borqZJ+zhWEEzr/IdxTKlNAoGBAJ7XbsjOuHSoPsB5ewsqMiBOj6b4FrwW1HK5gE/zszqtTZmmJqJdywuVQOI+hHq1IMJcge08uFDHvfES0ur1X18qfjloKHccw+RFKRMD/sYE6tBiZj8to0AzFWnMEFLVHcGhm16PT+riLbf1h7urX3u+hee3ZhbKsVgvAM6poZpJ
RSA_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiFlpkezayTgOM5BEpAf8+XRMNaF46vEsxEM3SHNEdDU1UMDBawyf1utdX9qLNxiCcqhWVSEYv1J75ZK79k7FnYsSU3V4yjFSVx3z3WgjYu8waU2YUdJR6s1+iLI3p9GnlYsgBTGEkHM6DEkJbnd2crntSg6BImn3MbB43necOaRQ7re/r1/KyOem/wi3Ye8jQIyUNIUZZ3Itgl4QXomCiLLDdkyY+GDdsVKY7wi2aUBFze0rdAcQWZnr/Na2XHd3nSpvLWuabS78K2GMv3firo5o7NSVkEPBtZX2DC/a/ZZWU1VF27zhTTkPjA/eyrnL+2i5srPEg0yjNnplbIYUIwIDAQAB

# MongoDB
MONGO_INITDB_ROOT_USERNAME=elise
MONGO_INITDB_ROOT_PASSWORD=elise
MONGO_INITDB_DATABASE=submission_service_db

# Redis
REDIS_PASSWORD=elise

# Kafka
KAFKA_BROKER_ID=1
KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
KAFKA_LISTENER_PORT=9092
KAFKA_LISTENER_NAME=PLAINTEXT
KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

# Spring Apps
SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
SPRING_DATA_MONGODB_URI=mongodb://elise:elise@mongodb:27017/submission_service_db?authSource=admin

# Zookeeper
ZOOKEEPER_CLIENT_PORT=2181
ZOOKEEPER_TICK_TIME=2000

ISSUER_URL=http://user-service:8080