spring:
  cloud:
    consul:
      host: consul
      port: 8500

  rabbitmq:
    host: localRabbitMQ
    port: 5672
    username: user
    password: password

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: submission_service_db
      username: elise
      password: elise
      authentication-database: submission_service_db

    redis:
      host: redis
      port: 6379
      password: elise

  kafka:
    bootstrap-servers: kafka:9092