CREATE TYPE status AS ENUM ('TODO', 'ATTEMPTED', 'SOLVED');
CREATE TYPE difficulty AS ENUM ('EASY', 'MEDIUM', 'HARD');
CREATE TYPE solution_type AS ENUM ('BRUTE_FORCE', 'OPTIMAL', 'EDITORIAL');
CREATE TYPE publish_status AS ENUM ('NOT_PUBLISHED', 'PUBLISHING', 'PUBLISHED', 'FAILED');